name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  solution: src/Kimera.sln
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  kimeraVersion: '0.8.72'
  kimeraDataVersion: '0.8.72'
  kimeraIOVersion: '0.8.72'
  kimeraNetworkVersion: '0.8.72'

jobs:
  build:
    if: ${{ github.repository == 'project-kimera/kimera' }}
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"

    - name: Restore dependencies
      run: dotnet restore ${{ env.solution }}

    - name: Build x86
      run: dotnet build ${{ env.solution }} --configuration ${{ env.buildConfiguration }} --no-restore -p:Platform="x86" -p:KimeraVersion=${{ env.kimeraVersion }}.${{ github.run_number }} -p:KimeraDataVersion=${{ env.kimeraDataVersion }}.${{ github.run_number }} -p:KimeraIOVersion=${{ env.kimeraIOVersion }}.${{ github.run_number }} -p:KimeraNetworkVersion=${{ env.kimeraNetworkVersion }}.${{ github.run_number }} -p:TreatWarningsAsErrors=True
      
    - name: Build x64
      run: dotnet build ${{ env.solution }} --configuration ${{ env.buildConfiguration }} --no-restore -p:Platform="x64" -p:KimeraVersion=${{ env.kimeraVersion }}.${{ github.run_number }} -p:KimeraDataVersion=${{ env.kimeraDataVersion }}.${{ github.run_number }} -p:KimeraIOVersion=${{ env.kimeraIOVersion }}.${{ github.run_number }} -p:KimeraNetworkVersion=${{ env.kimeraNetworkVersion }}.${{ github.run_number }} -p:TreatWarningsAsErrors=True

    #- name: Test
    #  run: dotnet test ${{ env.solution }} --configuration ${{ env.buildConfiguration }} --no-build --verbosity detailed --blame-crash
      
    - name: Upload x86 distribution files
      uses: actions/upload-artifact@v2
      with:
        name: Kimera v${{ env.kimeraVersion }} x86(i386)
        path: "src/Kimera/bin/x86/Release/net6.0-windows"
        
    - name: Upload x64 distribution files
      uses: actions/upload-artifact@v2
      with:
        name: Kimera v${{ env.kimeraVersion }} x64(AMD64)
        path: "src/Kimera/bin/x64/Release/net6.0-windows"
